version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: learn-skill-db
    environment:
      SA_PASSWORD: "PASSword123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: 
      context: .
      dockerfile: Dockerfile  # Nombre del Dockerfile
    container_name: learn-skill-api
    restart: always
    environment:
      ConnectionStrings__QuizAPIConnectionString: "Host=db;Port=1433;Database=SkillsDb;Username=possatgres;Password=PASSword123#"
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  sql_data:
