name: Build and Test

on:
  push:
      branches:
        - main
  workflow_dispatch:
  
jobs:
  build:
    name: Restore and Build
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore